### ISSUE TITLE
Error: malformed path data

### ISSUE THREAD

**Issue by khusamov** [rveciana/svg-path-properties#25]
SVG path:

```
<path d="M5445.85 4213.32a2595.99 2595.99 0 100 5191.98 2595.99 2595.99 0 100-5191.98z"/>
```

Code:

```typescript
import {svgPathProperties} from 'svg-path-properties';

svgPathProperties(pathNode.getAttribute('d')).getTotalLength()
```

Error:

```
(node:21788) UnhandledPromiseRejectionWarning: Error: malformed path data
    at C:\@repositories\svg-path-length\node_modules\svg-path-properties\build\path-properties.js:33:16
    at String.replace (<anonymous>)
    at parse (C:\@repositories\svg-path-length\node_modules\svg-path-properties\build\path-properties.js:16:8)
    at svgProperties (C:\@repositories\svg-path-length\node_modules\svg-path-properties\build\path-properties.js:635:19)

```

Bug?

**Comment by khusamov** [comment]
Is the problem taken from `parse-svg-path`? Create issue:
https://github.com/jkroso/parse-svg-path/issues/4

**Comment by rveciana** [comment]
I think that the path is incorrect. Inkscape doesn't draw it, nor any editor I've tried. Are you sure that is a corrrect path?

**Comment by khusamov** [comment]
> ... Are you sure that is a corrrect path?

Yes! The path is displayed correctly in Google Chrome.

**Comment by khusamov** [comment]
Still the same problem with arc:
```
M20087.17 6439.83c-166.45,-418.66 -251.94,-865.09 -251.94,-1315.61 0,-1966.61 1594.26,-3560.87 3560.87,-3560.87
```

**Comment by rveciana** [comment]
The problem is passing 9 arguments to the arc order. All the documentation I find says it's seven: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#Elliptical_Arc_Curve


> Is the problem taken from `parse-svg-path`? Create issue:
> [jkroso/parse-svg-path#4](https://github.com/jkroso/parse-svg-path/issues/4)

Yes, it's the same problem.

When adding two more arguments, a new arc is created, but I don't find the documentation where this is explained. I'll have to look more.

**Comment by rveciana** [comment]
Sorry, the example has 10 arguments, not 9.
The second example has 12 arguments instead of 6. This seems as a repetition, a behaviour different from the first example.
