### ISSUE TITLE
problems with quad curves degenerated into lines

### ISSUE THREAD

**Issue by gojko** [rveciana/svg-path-properties#9]
Hi,

I'm using version 0.2.1 from NPM, and it seems to have trouble working with degenerated quadratic curves (eg 'M60,20Q60,20 150,20'). 

```
var p = require('svg-path-properties')
props = p.svgPathProperties('M60,20Q60,20 150,20')
console.log(props.getTotalLength())
> NaN
props.getPointAtLength(2)
> TypeError: Cannot read property 'getPointAtLength' of undefined
    at Function.svgProperties.getPointAtLength (/Users/gojko/work/mindmup/mindmup-svg/node_modules/svg-path-properties/build/path-properties.js:787:37)
    at repl:1:7
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:538:10)
    at emitOne (events.js:101:20)
```
this produces NaN. Chrome, FireFox and Safari render this nicely as a line, report the length and work out the points at length.

**Comment by rveciana** [comment]
Thank you! I think that I've solved it in the last version, for Q and q curves. I have to check the equivalent case for C and c

**Comment by gojko** [comment]
lovely, thanks for such a fast response.
